// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB-HyjwpaC5dx_mPZ8W1y6qbTToF6ROIE',
    appId: '1:504736964361:web:0b57a159877c41ece3bdd8',
    messagingSenderId: '504736964361',
    projectId: 'flast-chat-angela-example',
    authDomain: 'flast-chat-angela-example.firebaseapp.com',
    storageBucket: 'flast-chat-angela-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf1nfoTTkVbgGPj3UL0s3NNk8sCGx45Oo',
    appId: '1:504736964361:android:1708957fe9e9ddcfe3bdd8',
    messagingSenderId: '504736964361',
    projectId: 'flast-chat-angela-example',
    storageBucket: 'flast-chat-angela-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANSqDUbRswCj9CZk636bqpCWwSXG402zg',
    appId: '1:504736964361:ios:6e8841bc78efabfde3bdd8',
    messagingSenderId: '504736964361',
    projectId: 'flast-chat-angela-example',
    storageBucket: 'flast-chat-angela-example.appspot.com',
    iosBundleId: 'com.example.flastChatFirebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANSqDUbRswCj9CZk636bqpCWwSXG402zg',
    appId: '1:504736964361:ios:7735e458d946133de3bdd8',
    messagingSenderId: '504736964361',
    projectId: 'flast-chat-angela-example',
    storageBucket: 'flast-chat-angela-example.appspot.com',
    iosBundleId: 'com.example.flastChatFirebaseExample.RunnerTests',
  );
}
